### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by RedxzAnomaly**

### CODE REVIEW

**Comment by DeviceIoControl** [comment]
Thank you very much for this PR, I've not had the time to do this, so it is appreciated.

Could you also state that the "InsydeDHCU.dll" is required (to be in the same directory as KBInsydeColours,exe) for people who have Single-Zone keyboards.

**Comment by RedxzAnomaly** [comment]
gonna state that now

**Comment by RedxzAnomaly** [comment]
Done, i hope u liked it 👍

**Comment by DeviceIoControl** [comment]
Perfect, I'm happy for you to merge that.

**Comment by DeviceIoControl** [comment]
Oh, that's interesting. OK, I will need to sort that out at some point, but I will merge this in for now.

**Pull request merged**
